services:
  back:
    build: 
      context: ./back
      dockerfile: Dockerfile
    container_name: golang-web
    ports:
      - "8080:8080"
    volumes:
      - ./back:/app
    environment:
      - CGO_ENABLED=1
    restart: on-failure

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "8000:8000"
    volumes:
      - ./front:/app
      - /app/node_modules
    tty: true

  microservices:
    build:
      context: ./microservices
      dockerfile: Dockerfile
    container_name: microservices
    env_file:
      - ./microservices/.env
    ports:
      - "8001:8001"
    tty: true