version: '3.8'

services:
  back:
    image: smartepicroadtrip.azurecr.io/t-web-800-ren_8-back:latest
    container_name: golang-web
    ports:
      - "8080:8080"
    environment:
      - CGO_ENABLED=1
    restart: on-failure

  front:
    image: smartepicroadtrip.azurecr.io/t-web-800-ren_8-front:latest
    container_name: front
    ports:
      - "8000:8000"
    tty: true

  microservices:
    image: smartepicroadtrip.azurecr.io/t-web-800-ren_8-microservices:latest
    container_name: microservices
    env_file:
      - ./microservices/.env
    ports:
      - "8001:8001"
    tty: true
