version: '3.8'

services:
  back:
    image: smartepictripacr.azurecr.io/backend:latest
    container_name: golang-web
    ports:
      - "8080:8080"
    environment:
      - CGO_ENABLED=1
    restart: on-failure

  front:
    image: smartepictripacr.azurecr.io/frontend:latest
    container_name: front
    ports:
      - "8000:8000"
    tty: true

  microservices:
    image: smartepictripacr.azurecr.io/microservices:latest
    container_name: microservices
    env_file:
      - ./microservices/.env
    ports:
      - "8001:8001"
    tty: true
