name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/back:latest ./back
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/front:latest ./front
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/microservices:latest ./microservices

          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/back:latest
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/front:latest
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/microservices:latest

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: |
            ${{ secrets.AZURE_CONTAINER_REGISTRY }}/back:latest
            ${{ secrets.AZURE_CONTAINER_REGISTRY }}/front:latest
            ${{ secrets.AZURE_CONTAINER_REGISTRY }}/microservices:latest
